FROM registry.git.ee.ethz.ch/pbl/research/robodog/ros_base_layers/ros_humble


# install lightglue
WORKDIR /lightglue
RUN git clone https://github.com/cvg/LightGlue.git && \
    cd LightGlue && \
    pip install -e .

# Use opencv installation from source of the base layer
RUN pip uninstall -y opencv-python

WORKDIR $ROS_WS
COPY gaze_transform_lightglue $ROS_WS/src/gaze_transform_lightglue/
RUN cd $ROS_WS/src/ && \
    git clone git@git.ee.ethz.ch:pbl/research/smart-glasses/gaze_tracking/ros2_msgs.git
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build

USER $USER_NAME
