version: '3.6'
services:
  pupil_labs_glasses:
    container_name: pupil_labs_glasses
    image: registry.git.ee.ethz.ch/pbl/research/smart-glasses/robodog_control/pupil_labs_glasses:feature.robodog_integration
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /dev:/dev
    entrypoint: /entrypoint.sh ros2 launch pupil_labs_glasses pupil_labs_stream.yaml "pupillabs_ip_addr:=10.5.50.42"
    restart: on-failure