version: '3.6'
services:
  robodog_control_dev:
    container_name: robodog_control_dev
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile.dev
      args:
        IMAGE: ros_humble
    image: robodog_control_dev
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /dev:/dev
      - ../gaze_transform:/ws/src/gaze_transform
      - ../gaze_transform_lightglue:/ws/src/gaze_transform_lightglue
      - ../pupil_labs_glasses:/ws/src/pupil_labs_glasses
      - ../robodog_control:/ws/src/robodog_control
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # WSL specific
      - /usr/lib/wsl:/usr/lib/wsl
    environment:
      - DISPLAY=$DISPLAY
      # - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/.X11-unix
      - ROS_HOSTNAME=localhost
      # WSL specific
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    command: /bin/sh -c "while sleep 1000; do :; done"
    restart: no
