FROM registry.git.ee.ethz.ch/pbl/research/robodog/ros_base_layers/ros_humble

WORKDIR $ROS_WS
COPY pupil_labs_glasses $ROS_WS/src/pupil_labs_glasses/
RUN cd $ROS_WS/src/ && \
    git clone git@git.ee.ethz.ch:pbl/research/smart-glasses/gaze_tracking/ros2_msgs.git
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build

USER $USER_NAME