version: '3.6'
services:
  robodog_control:
    container_name: robodog_control
    image: registry.git.ee.ethz.ch/pbl/research/smart-glasses/robodog_control/robodog_control 
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /dev:/dev
    entrypoint: /entrypoint.sh ros2 launch robodog_control robodog_control.yaml
    restart: on-failure