version: '3.6'
services:
  gaze_transform:
    container_name: gaze_transform
    image: registry.git.ee.ethz.ch/pbl/research/smart-glasses/robodog_control/gaze_transform
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /dev:/dev
    entrypoint: /entrypoint.sh ros2 launch gaze_transform gaze_transform.yaml
    restart: on-failure