ARG IMAGE=ros_humble
FROM registry.git.ee.ethz.ch/pbl/research/robodog/ros_base_layers/${IMAGE}

# install lightglue
WORKDIR /lightglue
RUN git clone https://github.com/cvg/LightGlue.git && \
    cd LightGlue && \
    pip install -e .

RUN mkdir -p /python_packages \
    && cd /python_packages \
    && git clone https://github.com/paulijosey/realtime-python-api.git \
    && cd realtime-python-api \
    && git checkout fix/imuData \
    && pip install -e .

# Use opencv installation from source of the base layer
RUN pip uninstall -y opencv-python

WORKDIR $ROS_WS
COPY gaze_transform_lightglue $ROS_WS/src/gaze_transform_lightglue/
COPY robodog_control $ROS_WS/src/robodog_control/
COPY pupil_labs_glasses $ROS_WS/src/pupil_labs_glasses/
COPY gaze_transform $ROS_WS/src/gaze_transform/
RUN cd $ROS_WS/src/ && \
    git clone git@git.ee.ethz.ch:pbl/research/smart-glasses/gaze_tracking/ros2_msgs.git
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build

USER $USER_NAME
